### ISSUE TITLE
How can I use other channel(like Tangent) to blend more textures? 

### ISSUE THREAD

**Issue by OtakuAndFitness** [needle-mirror/com.unity.polybrush#1]
I wanna blend like 12 textures in my custom shader. Then I tried to add an attribute like this
![无标题](https://user-images.githubusercontent.com/9075980/134790446-b39ba4d5-2f03-4811-8a60-8d218cec180e.png)

However, there is an error occurred when I selected the new texture
![无标题](https://user-images.githubusercontent.com/9075980/134790460-c4702993-cb87-44ae-b252-b9af72b7bbe3.png)

As a result, I can't use tangent channel to blend more textures. Is there anything I can do in my custom shader?

**Comment by marwie** [comment]
Hello @OtakuAndFitness

Please report this issue as a bug to Unity. We're not officially associated with Unity and only mirror the packages but we do not develop them. So to get a response and help from Unity you must use the official bug reporter. I'm sorry that I can't help directly

Please see the following link on how to report a bug: https://support.unity.com/hc/en-us/articles/206336985-How-do-I-submit-a-bug-report-#:~:text=Click%20on%20Help%20and%20select,to%20submit%20your%20bug%20report.
